### ISSUE TITLE
How do I use the object constructor to get data from two existing variables?

### ISSUE THREAD

**Issue by walter-0** [ga-dc/project1#103] opened 2015-07-14 15:00 UTC
https://github.com/Walter-0/project1/blob/master/script.js#L28-L31

I'm trying to create an object, highScores, that takes data from two variables, user and finalScore, to create an object constructor that creates objects of each user and their score. I'm trying to make the High Score button alert this object and all key/value pairs inside it.

**Comment by jshawl** [comment] 2015-07-14 15:17
sorry im not understanding what the issue is

**Comment by walter-0** [comment] 2015-07-14 15:19
I want to know how to use the object constructor to take two arguments which are defined variables. So something like user1:score1 user2:score2 etc.

**Comment by jshawl** [comment] 2015-07-14 15:22
``` js
var User = function( arg1, arg2){
  this.name = arg1
  this.score = arg2
}

var user = new User("Jesse", 13)
console.log(user)
```

Like this? http://repl.it/wyo

**Comment by walter-0** [comment] 2015-07-14 15:43
I've tried this
var ranking = function( user, finalScore){
  this.name = user
  this.score = finalScore
}
//high score button
$("#highScore").click(function(){
  var ranking1 = new ranking(user, finalScore)
  alert(ranking1)
})

No errors, but clicking high score alerts [object Object]

**Comment by jshawl** [comment] 2015-07-14 15:46
yes! perfect! [object Object] is the string representation of a JS object. try using console.log to see its keys and values.

closing for now because your code looks right, but feel free to reopen

**Closed as completed by jshawl** 2015-07-14 15:46 UTC
